name = "sts-generator"
main = "src/index.tsx"
compatibility_date = "2023-01-25"
keep_vars = true

routes = [
	{ pattern = "sts.lenster.xyz", custom_domain = true }
]

[env.production.vars]
RELEASE = ""
EVER_ACCESS_KEY = ""
EVER_ACCESS_SECRET = ""
